### ISSUE TITLE
Unable to Install flowbit blade icons

### ISSUE THREAD

**Issue by jawadk116** [themesberg/flowbite-blade-icons#4]
after installing fresh laravel 11 in my windows 11 machine.

 composer require themesberg/flowbite-blade-icons
 
 composer output:
 
 Using version ^1.0 for themesberg/flowbite-blade-icons
./composer.json has been updated
Running composer update themesberg/flowbite-blade-icons
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires themesberg/flowbite-blade-icons ^1.0 -> satisfiable by themesberg/flowbite-blade-icons[v1.0.0, v1.0.1, v1.0.2].
    - themesberg/flowbite-blade-icons[v1.0.0, ..., v1.0.2] require illuminate/support ^9.0|^10.0 -> found illuminate/support[v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.11] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require themesberg/flowbite-blade-icons:*" to figure out if any version is installable, or "composer require themesberg/flowbite-blade-icons:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by zoltanszogyenyi** [comment]
Hey @domthomas-dev,

Is this some thing local or generalized?

**Comment by adesmuoih** [comment]
Looks as it was already fixed in the main branch but not tagged and not available via packagist?
verified: installation works with:
```bash
composer require themesberg/flowbite-blade-icons @dev
```

**Comment by domthomas-dev** [comment]
Hi @zoltanszogyenyi 
https://github.com/themesberg/flowbite-blade-icons/releases/tag/v1.1.0

Thanks @adesmuoih, right, I forget the release
